### ISSUE TITLE
Implementing Video Calling feature in a new App

### ISSUE THREAD

**Issue by mrmadhav** [ConnectyCube/connectycube-flutter-samples#159] opened 2021-10-25 07:05 UTC
**Specify the sample to which the issue belongs (use [x]):**
[] Chat sample
[x] P2P Call sample
[] Conference Call sample

**Platform (use [x])**
[x] Android
[x] iOS
[] macOS
[] Windows
[] Web

**Device info**
Manufacture: Apple / Huawei
Model: iPhone X / Huawei P30 Pro
OS version: iOS 15 /  Android 10

**Describe the bug:**
Hi, I used the P2P Call Sample as example to add the Video Calling feature into my App.

Until now, when I am inside the App, I properly get the calls when someone is calling. However, I do not get any push notifications nor does the App wake up when closed.

I have set up Firebase and Apple VOIP APNS on Connectycube.

**Comment by TatankaConCube** [comment] 2021-11-10 13:54
any updates?

**Comment by mrmadhav** [comment] 2021-11-10 19:02
Yes, this issue was happening as I was not setting the name of the user on ConnectyCube. I have changed that code to use the name from my App directly.

Right now, everything seems to be working, the calls on iOS and Android. Howewer, I do have a couple of issues that seem to be happening intermittently and which is really bad for the user experience:
1. Sometimes, the video does not activate on one of the users, we just see a blank space where that person's video should have been. It seems to be happening a lot when on 4G or not so good Wifi connections. However, if the Wifi connection is great, I do not have this issue.
2. Sometimes, when the call is coming in, if I take it from the OS calling screen, it does not activate inside the app and nothing happens. On iPhones, you can actually see that a call is ongoing somewhere (via the green top bar on iOS), but we cannot access the call from anywhere.
3. On huawei devices(I have tested on 2 devices right now), as soon as the app tries to activate the camera, it crashes completely. As such the calls do not work.

I am in between projects right now, so not able to give 100% time on this project specifically, but will need to resolve these issues. So will be debugging this in the coming weeks.

**Comment by TatankaConCube** [comment] 2022-01-05 17:06
try the latest version of our SDK, if the issue is still actual, create a new ticket with details, closing

**Closed by TatankaConCube** 2022-01-05 17:06 UTC
