### ISSUE TITLE
push error FormatException: Invalid character (at character 1)

### ISSUE THREAD

**Issue by zhukeev** [ConnectyCube/connectycube-flutter-samples#111] opened 2021-07-27 04:47 UTC
**Specify the sample to which the issue belongs (use [x]):**
[X] Chat sample
[ ] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[X] Android
[ ] iOS

**Device info**
Manufacture: Xiaomi
Model: Note 5
OS version: 9

**Describe the bug:**
can't send notificaions

**Steps to Reproduce:**
1. 
2.
3.
4.

**Logs:**
```

I/flutter (15275): CB-SDK: : *********************************************************
I/flutter (15275): *** RESPONSE *** 201 *** 6cbff993-8691-4a88-b571-516b407cda31 ***
I/flutter (15275): HEADERS
I/flutter (15275):   {cb-token-expirationdate: 2021-07-27 06:43:18 UTC, connection: keep-alive, date: Tue, 27 Jul 2021 04:43:18 GMT, content-length: 5127, strict-transport-security: max-age=15768000; includeSubDomains, content-type: application/json; charset=utf-8, server: nginx/1.16.1}
I/flutter (15275): BODY
I/flutter (15275):   [{"event":{"_id":"60ff8ee671b8cd00342113ec","event_type":"one_shot","message":"eyJpb3NfY2F0ZWdvcnkiOiJNRUVUSU5HX0lOVklUQVRJT04iLCJpb3Nfdm9pcCI6MSwibm90aWZpY2F0aW9uX3R5cGUiOiJuZXdNZXNzYWdlIiwiY29udGVudC1hdmFpbGFibGUiOjEsInRpdGxlIjoiQXJnZW4iLCJpZCI6ODg1ODQxMDE1LCJkYXRldGltZSI6IjIwMjEtMDctMjdUMTA6NDM6MTYuNjU4NDA3Iiwic2VuZGVyX3VzZXIiOnsiZnVsbF9uYW1lIjoiQXJnZW4iLCJhZGRyZXNzX2Jvb2tfbmFtZSI6bnVsbCwiZW1haWwiOm51bGwsImxvZ2luIjoiNjBjMWE1Y2I3ZDU2OCIsInBob25lIjpudWxsLCJ3ZWJzaXRlIjpudWxsLCJsYXN0X3JlcXVlc3RfYXQiOiIyMDIxLTA3LTI3VDA0OjQxOjI5LjAwMFoiLCJleHRlcm5hbF91c2VyX2lkIjpudWxsLCJmYWNlYm9va19pZCI6bnVsbCwidHdpdHRlcl9pZCI6bnVsbCwiY3VzdG9tX2RhdGEiOm51bGwsImF2YXRhciI6Imh0dHBzOi8vc3RhZ2UucHJpdmF0ZXRoZXJhcHljbGluaWMuY29tL3N0b3JhZ2UvY2xpZW50UHJvZmlsZUltYWdlcy8yNTZfNjBmOGYzMDlkODBhNS5wbmciLCJ0YWdfbGlzdCI6bnVsbCwiaWQiOjQ0MDg1MjgsImNyZWF0ZWRfYXQiOiIyMDIxLTA2LTEwVDA1OjQwOjI3LjAwMFoiLCJ1cGRhdGVkX2F0IjoiMjAyMS0wNy0yN1QwNDo0MToyOS4wMDBaIn0sImRpYWxvZ19pZCI6IjYwZjY1Y2NjMjg4OWE3MDAxMmUzMDRlOCIsIm1lc3NhZ2UiOiLQuNGC0YwifQ==","user_id":44
I/flutter (15275):
I/flutter (15275):  push error FormatException: Invalid character (at character 1)
I/flutter (15275): =
I/flutter (15275): ^
I/flutter (15275):  push {ios_category: MEETING_INVITATION, ios_voip: 1, notification_type: newMessage, content-available: 1, title: Argen, id: 885841015, datetime: 2021-07-27T10:43:16.658407, sender_user: {full_name: Argen, address_book_name: null, email: null, login: 60c1a5cb7d568, phone: null, website: null, last_request_at: 2021-07-27T04:41:29.000Z, external_user_id: null, facebook_id: null, twitter_id: null, custom_data: null, avatar: https://stage.privatetherapyclinic.com/storage/clientProfileImages/256_60f8f309d80a5.png, tag_list: null, id: 4408528, created_at: 2021-06-10T05:40:27.000Z, updated_at: 2021-07-27T04:41:29.000Z}, dialog_id: 60f65ccc2889a70012e304e8, message: ить}
```
or
[Gist log](https://gist.github.com/)

**Actual result:**

**Expected behavior:**

**Additional info**

**Comment by TatankaConCube** [comment] 2021-07-28 13:34
@zhukeev please attach the full log from the flutter console without any filters.

**Comment by TatankaConCube** [comment] 2021-09-02 14:58
should be fixed in the latest SDK version, try it. Create a new ticket with more details if the issue is still actual in the latest version. Closing this ticket.

**Closed by TatankaConCube** 2021-09-02 14:58 UTC
