### ISSUE TITLE
Firebase authentication

### ISSUE THREAD

**Issue by najibghadri** [ConnectyCube/connectycube-flutter-samples#13] opened 2020-07-10 11:18 UTC
Firebase has an extensive authentication system and a broadly used flutter package for it, [firebase_auth](https://pub.dev/packages/firebase_auth). What if I want to authenticate my already existing firebase users (not only with phone, but with social firebase integrations) in your system? I did not find a tutorial to this and I think this would be more widely used instead of only using your authentication.

I found [flutter authentication-and-users](https://developers.connectycube.com/flutter/authentication-and-users) site that explains firebase phone signin, and [External authentication via Custom Identity Provider](https://developers.connectycube.com/guides/custom-identity-provider), but is there a function that let's me simply authenticate with firebase and use those credentials with connectycube? 

In the [SDK reference](https://pub.dev/documentation/connectycube_sdk/latest/connectycube_sdk/connectycube_sdk-library.html) it seems like you only support firebase phone tokens. **So how to integreate full firebase authentication?**

**Comment by najibghadri** [comment] 2020-07-15 10:16
Hello!

**Comment by TatankaConCube** [comment] 2020-07-15 10:49
hello @najibghadri, sorry for long time answer, Connectycube API supports authentication via firebase phone auth only. But you can use [Custom Identity Provider feature](https://developers.connectycube.com/flutter/authentication-and-users?id=authentication-via-external-identity-provider) to implement own provider for authentication users via firebase and save them on Connectycube server.

**Comment by najibghadri** [comment] 2020-07-15 12:07
I found that, but I think there could be a simpler way. Anyways, thanks! :)

**Comment by TatankaConCube** [comment] 2020-07-23 19:12
Looks like the issue is resolved, so closing it.

**Closed by TatankaConCube** 2020-07-23 19:12 UTC
