### ISSUE TITLE
Build IOS Release

### ISSUE THREAD

**Issue by nambui2000k** [ConnectyCube/connectycube-flutter-samples#160] opened 2021-10-29 20:56 UTC
**Specify the sample to which the issue belongs (use [x]):**
[] Chat sample
[x] P2P Call sample
[] Conference Call sample

**Platform (use [x])**
[] Android
[x] iOS
[] macOS
[] Windows
[] Web

**Device info**
Manufacture: 
Model: 
OS version:

**Describe the bug:**
When run Archive I has error : 'WebRTC/WebRTC.h' file not found. Can you resolve?

**Steps to Reproduce:**
1. open xCode
2. Choose tab Product
3. Archive

**Logs:**
```
log here
```
or
[Gist log](https://gist.github.com/)

**Actual result:**

![Screen Shot 2021-10-30 at 04 06 49](https://user-images.githubusercontent.com/49670327/139501672-035646bd-c317-4855-bf3d-0ab1ec0eac45.png)

**Expected behavior:**

**Additional info**

**Comment by mrmadhav** [comment] 2021-10-30 17:50
Click on the 'flutter_webrtc' item on your left column. It should bring you to the PODS project. There in Build Settings, set 'Build Active Architecture Only' -> Release -> Yes

![image](https://user-images.githubusercontent.com/6939434/139543734-6d49c5f2-9758-4a61-b35d-aaadf61257b4.png)

**Comment by nambui2000k** [comment] 2021-10-30 17:53
![Screen Shot 2021-10-31 at 00 53 33](https://user-images.githubusercontent.com/49670327/139543985-d7239d0b-43d9-4e29-ae00-ec4e6ecdea6f.png)

Not change

**Comment by mrmadhav** [comment] 2021-10-30 18:13
Try setting it on the 'Pods' Project instead so that it applies to all pods in the project. Check my screenshot again.

That was the only way that I was able to get it to work for me.

**Comment by nambui2000k** [comment] 2021-10-30 18:17
![Screen Shot 2021-10-31 at 01 16 53](https://user-images.githubusercontent.com/49670327/139553936-31f883a0-f367-486e-b23c-8b3d2fb165b2.png)
It still doesn't work

**Comment by mrmadhav** [comment] 2021-10-30 18:19
You do not seem to have an iPhone plugged in. This may be what is causing the issue. The WebRTC package works only for arm64 and will not compile for armv7.

When you plug in an iPhone, the current architecture becomes arm64 and thus the build should pass.

**Comment by nambui2000k** [comment] 2021-10-30 18:21
Yes. I run it in an iPhone. it pass. But I want to build Archive to release app to TestFlight.

**Comment by mrmadhav** [comment] 2021-10-30 18:23
When you are archiving, keep your iphone plugged in, and make sure that the top of xcode looks like this:
![image](https://user-images.githubusercontent.com/6939434/139554134-52fa7e6d-cf8d-4888-94a9-dc620b5c40a0.png)

**Comment by nambui2000k** [comment] 2021-10-30 18:34
![Screen Shot 2021-10-31 at 01 34 06](https://user-images.githubusercontent.com/49670327/139554442-2a4bb74e-c921-496b-875d-a1476bcf89f6.png)
looks like?

**Comment by mrmadhav** [comment] 2021-10-30 18:37
In your final screenshot, you have the wrong value for 'Build Active Architecture Only'. It should be set to 'Yes'.

In summary, make sure you have your iPhone plugged in + 'Build Active Architecture Only' set to 'Yes' for all profiles.

**Comment by nambui2000k** [comment] 2021-10-30 18:41
![Screen Shot 2021-10-31 at 01 41 26](https://user-images.githubusercontent.com/49670327/139554942-19b3b195-a7c9-45a5-99c9-4d4a7bc5e3f0.png)
I has error?

**Comment by TatankaConCube** [comment] 2021-11-02 11:29
@nambui2000k after some investigation, we found that this issue is related to the `flutter_webrtc` which we use in our SDK. Its developers know about it and have the solution for it, but still don't release it. As a workaround use the previous version of our SDK `connectycube_sdk: 2.0.5`.

**Comment by nambui2000k** [comment] 2021-11-08 09:52
> @nambui2000k after some investigation, we found that this issue is related to the `flutter_webrtc` which we use in our SDK. Its developers know about it and have the solution for it, but still don't release it. As a workaround use the previous version of our SDK `connectycube_sdk: 2.0.5`.
flutter_webrtc has had new version. can you check it to solve my issue?

**Comment by TatankaConCube** [comment] 2021-11-08 09:55
we saw it, we'll check it soon

**Comment by nambui2000k** [comment] 2021-11-08 09:56
> we saw it, we'll check it soon

tks so much

**Comment by TatankaConCube** [comment] 2021-11-09 09:21
the new version works fine, will publish the new version of our SDK with it in a few days

**Comment by nambui2000k** [comment] 2021-11-09 09:22
> the new version works fine, will publish the new version of our SDK with it in a few days

oh. 👍  thanks

**Comment by TatankaConCube** [comment] 2021-11-10 09:42
@nambui2000k the versin [2.0.7](https://pub.dev/packages/connectycube_sdk/versions/2.0.7) was released, try it. If issue war resolved, please close this ticket.

**Closed** 2021-11-12 07:02 UTC

**Comment by gimon1156** [comment] 2021-12-02 01:36
@TatankaConCube Hi, I am using the 2.0.7 but still having same issues of this.

Both me and my team are unable to run the project

**Comment by benz93chung** [comment] 2021-12-02 05:14
I can attest to @gimon1156 's comments that the issue is still persisting with 2.0.7.

<b>Specify the sample to which the issue belongs (use [x]):</b>
[x] Chat sample
[ ] P2P Call sample
[ ] Conference Call sample

<b>Platform (use [x])</b>
[] Android
[x] iOS

<b>Device info</b>
iOS Simulator

<b>Describe the bug:</b>
An error has occurred upon building for iOS. WebRTC is also said to be not found. The 'Build Active Architecture Only' onto Pods and flutter_webrtc also did not make a difference.

<b>Steps to Reproduce:</b>
1. Clone the sample
2. Update SDK to 2.0.7. Also update the Firebase dependencies
3. Build and run

<b>Log</b>
```
Launching lib/main.dart on iPhone 13 Pro Max in debug mode...
Xcode build done.                                           11.9s
Failed to build iOS app
Error output from Xcode build:
↳
    --- xcodebuild: WARNING: Using the first of multiple matching destinations:
    { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
    { platform:iOS Simulator, id:E2BF18A2-F96E-49F1-B145-03236BD21F60, OS:15.0, name:iPad (9th generation) }
    { platform:iOS Simulator, id:5C61F1A6-25DE-4F3E-A2C3-D31285BB73EA, OS:15.0, name:iPad Air (4th generation) }
    { platform:iOS Simulator, id:6AC1B26C-6A04-4BB8-8BB9-4FD8986FAAA7, OS:15.0, name:iPad Pro (9.7-inch) }
    { platform:iOS Simulator, id:BC647483-FC68-48E3-9BA4-447701BA0124, OS:15.0, name:iPad Pro (11-inch) (3rd generation) }
    { platform:iOS Simulator, id:87FDF6B6-6040-4CBA-976D-75B3B384C1C6, OS:15.0, name:iPad Pro (12.9-inch) (5th generation) }
    { platform:iOS Simulator, id:5DC08B7A-3EBD-46C0-BC3A-8503D4B7F314, OS:15.0, name:iPad mini (6th generation) }
    { platform:iOS Simulator, id:9BE80A9A-0ED3-4065-82C9-7EC289D4A7AA, OS:15.0, name:iPhone 8 }
    { platform:iOS Simulator, id:101EEBB2-54AF-4A1A-8404-275EFB3AC043, OS:15.0, name:iPhone 8 Plus }
    { platform:iOS Simulator, id:2F97ECA3-C124-4352-ADB7-71F19CB30D3B, OS:15.0, name:iPhone 11 }
    { platform:iOS Simulator, id:FF29F4CB-6A09-499F-A8FB-69C9CF61A0E1, OS:15.0, name:iPhone 11 Pro }
    { platform:iOS Simulator, id:C264E9A8-2473-4741-96EE-7A36C415A5AB, OS:15.0, name:iPhone 11 Pro Max }
    { platform:iOS Simulator, id:7EC15D18-13D9-42C9-A215-6BB25EF8A401, OS:15.0, name:iPhone 12 }
    { platform:iOS Simulator, id:1965DE0D-22A1-4791-A361-2EDFBF40F577, OS:15.0, name:iPhone 12 Pro }
    { platform:iOS Simulator, id:018AFA59-5D61-431B-88A1-2BC5734DBB67, OS:15.0, name:iPhone 12 Pro Max }
    { platform:iOS Simulator, id:28B39743-DC36-45DC-A6AC-08F7B6380CCA, OS:15.0, name:iPhone 12 mini }
    { platform:iOS Simulator, id:F62E758F-C758-4068-9BAA-019A6FBA21E8, OS:15.0, name:iPhone 13 }
    { platform:iOS Simulator, id:7BA32B17-8083-47B3-914C-6DC3516744D5, OS:15.0, name:iPhone 13 Pro }
    { platform:iOS Simulator, id:6F3D9FEE-9BFA-4A85-870A-A5EFCA493C67, OS:15.0, name:iPhone 13 Pro Max }
    { platform:iOS Simulator, id:5222A1DE-5AFE-4776-80D6-C645B254192E, OS:15.0, name:iPhone 13 mini }
    { platform:iOS Simulator, id:D88F7050-86B0-46B9-958E-706627B42AC2, OS:15.0, name:iPhone SE (2nd generation) }
    { platform:iOS Simulator, id:C2063A91-B392-4D13-8204-0B272B0CCA9C, OS:15.0, name:iPod touch (7th generation) }
    { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
    ** BUILD FAILED **
Xcode's output:
↳
    warning: [CP] Unable to find matching .xcframework slice in 'ios-x86_64-simulator ios-arm64_armv7' for the current build architectures (arm64 x86_64 i386).
/Users/benjaminchung/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.7.1/ios/Classes/FlutterRTCMediaStream.m:3:9: fatal error: 'WebRTC/WebRTC.h' file not found
    #import <WebRTC/WebRTC.h>
            ^~~~~~~~~~~~~~~~~
    1 error generated.
In file included from /Users/benjaminchung/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.7.1/ios/Classes/FlutterRTCDataChannel.m:2:
In file included from /Users/benjaminchung/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.7.1/ios/Classes/FlutterRTCDataChannel.h:1:
/Users/benjaminchung/.pub-cache/hosted/pub.dartlang.org/flutter_webrtc-0.7.1/ios/Classes/FlutterWebRTCPlugin.h:8:9: fatal error: 'WebRTC/WebRTC.h' file not found
    #import <WebRTC/WebRTC.h>
            ^~~~~~~~~~~~~~~~~
    1 error generated.
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in parallel
    /Users/benjaminchung/Documents/repos/connectycube-flutter-samples/chat_sample/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'Reachability' from project 'Pods')
    /Users/benjaminchung/Documents/repos/connectycube-flutter-samples/chat_sample/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'FMDB' from project 'Pods')
    /Users/benjaminchung/Documents/repos/connectycube-flutter-samples/chat_sample/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'Toast' from project 'Pods')
    /Users/benjaminchung/Documents/repos/connectycube-flutter-samples/chat_sample/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'Libyuv' from project 'Pods')
    /Users/benjaminchung/Documents/repos/connectycube-flutter-samples/chat_sample/ios/Pods/Pods.xcodeproj: warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 8.0, but the range of supported deployment target versions is 9.0 to 15.0.99. (in target 'Flutter' from project 'Pods')
Could not build the application for the simulator.
Error launching application on iPhone 13 Pro Max.
Exited (sigterm)
```

<b>Actual result:</b>
https://photos.app.goo.gl/FKh419SMdc4AhgbM9
https://photos.app.goo.gl/WrFndVqCMj973LSg9
https://photos.app.goo.gl/Enhgm8eRpXRU4VqH6

<b>Expected behavior:</b>
Build successfully to simulator/device like before.

<b>Additional info</b>
N/A
