### ISSUE TITLE
Session expired after closing the application , even if does not cross 2hrs session expiration time

### ISSUE THREAD

**Issue by wrteam-priyansh** [ConnectyCube/connectycube-flutter-samples#46] opened 2020-12-10 09:51 UTC
Session expires after closing the application and also CubeChatConnection.instance.isAuthenticated() become false even after login..Is this expected behaviour or i am missing something

This is my login function..
//To login into connnectyCube
  static Future<void> loginToConnectyCube(BuildContext context) async {
    //Checking if session is valid or not
    CubeSession cubeSession = CubeSessionManager.instance.activeSession;

    if (CubeSessionManager.instance.isSessionExpired(cubeSession)) {
      print("Session is expired");
      //Id for connectyCube
      int id;
      //Current user's email id
      String userEmail = Constant.session.getData(UserSessionManager.KEY_EMAIL);

      //Fetching connectyCube user Id
      if (Constant.session.getIntData(UserSessionManager.KEY_CONNECTYCUBE_ID) !=
          0) {
        print("Getting connectyCube id from local storage");
        id =
            Constant.session.getIntData(UserSessionManager.KEY_CONNECTYCUBE_ID);
      } else {
        //check if user is register or not

        //Create session
        cubeSession = await createSession();
        print("Session created");
        CubeUser checkCubeUserExist =
            await checkUserAlreadyExistInConnectyCube();

        if (checkCubeUserExist == null) {
          print("Registering the user");

          CubeUser registeredCubeUser = await registerUserToConnectyCube(
              userid: Constant.session.getData(UserSessionManager.KEY_ID),
              email: userEmail,
              firstName: Constant.session.getData(UserSessionManager.KEY_FNAME),
              lastName: Constant.session.getData(UserSessionManager.KEY_LNAME),
              phone: Constant.session.getData(UserSessionManager.KEY_PHONE));
          id = registeredCubeUser.id;

          Constant.session.setIntData(
              UserSessionManager.KEY_CONNECTYCUBE_ID, registeredCubeUser.id);
        } else {
          //if user is already registered
          print("User is already registered");
          id = checkCubeUserExist.id;
          Constant.session.setIntData(
              UserSessionManager.KEY_CONNECTYCUBE_ID, checkCubeUserExist.id);
        }
      }
      print("Current user's connecty cube Id : $id");
      CubeUser loginUser = CubeUser(
          email: Constant.session.getData(UserSessionManager.KEY_EMAIL),
          login: connectyCubeLoginId(),
          id: id,
          password: ConnectyCube_DEFAULT_PASS);

      if (cubeSession == null) {
        //if session is not created before
        cubeSession = await createSession(loginUser);
        await CubeChatConnection.instance.login(loginUser);
      } else {
        await signIn(loginUser);
        await CubeChatConnection.instance.login(loginUser);
      }
    } else {
      print("Session is valid");
    }
  }

**Comment by TatankaConCube** [comment] 2020-12-14 09:30
@wrteam-priyansh first of all, sorry for a longtime answer. It happens because we don't save session data to storage only to variables and they clean by the system after the app destroy. You have the right logic for session managing, but your code can be simplified by using callback `restoreSession` which will be called if our SDK needs a session with a user. More by [link](https://developers.connectycube.com/flutter/authentication-and-users?id=session-expiration).

**Comment by wrteam-priyansh** [comment] 2020-12-14 09:47
@TatankaConCube Thanks for replying , i have used this code in order to restore session...
onSessionRestore: () async {
      if (Constant.session.getBoolData(UserSessionManager.IS_USER_LOGIN)) {
        print("User is logged in");
        CubeUser cubeUser = CubeUser(
            id: Constant.session
                .getIntData(UserSessionManager.KEY_CONNECTYCUBE_ID),
            email: Constant.session.getData(UserSessionManager.KEY_EMAIL),
            login: Constant.session
                .getData(UserSessionManager.KEY_CONNECTYCUBE_LOGIN),
            password: Constant.ConnectyCube_DEFAULT_PASS);

        return createSession(cubeUser);
      } else {
        print("User is logged not in");
      }
      return null;
    }
but still i have to follow the login process after closing the app.
Can you please tell me what is wrong in above mention code

**Comment by TatankaConCube** [comment] 2020-12-14 10:38
It is expected behavior when we create a new session after app closing. If you don't want to recreate the session after app closing, you can save the active session in storage then after app opening set it as an active session via:
```dart
CubeSession savedSession; // get saved session
CubeSessionManager.instance.activeSession = savedSession;
```

**Comment by wrteam-priyansh** [comment] 2020-12-14 10:50
@TatankaConCube Thanks for replying. will try this soon

**Comment by wrteam-priyansh** [comment] 2020-12-15 06:58
@TatankaConCube do we have to follow login process every time opens application?

**Comment by TatankaConCube** [comment] 2020-12-15 08:29
It is required if you use API calls. It needs to provide an additional security level for your app.

**Closed** 2020-12-31 13:23 UTC
