### ISSUE TITLE
Login takes 6 -15 seconds

### ISSUE THREAD

**Issue by shivanijha002** [ConnectyCube/connectycube-flutter-samples#73] opened 2021-03-18 17:09 UTC
CubeChatConnection.instance.login is taking 6-15 seconds for me even with 100mbps internet connectivity. This is experienced by all of my app user. I am getting negative feedback of app because of this slowness. Kindly help to optimize login experience.

Below is the code snippet used:
await createSession(user).then(
(cubeSession) async {
if (!CubeSessionManager.instance.isActiveSessionValid()) {
print('Session Invalid');
}
else {
if (CubeChatConnection.instance.chatConnectionState !=
CubeChatConnectionState.Ready) {
print("Log: Login start" + DateTime.now().toString());
await CubeChatConnection.instance
.login(user1)
.then((cubeUser) async {
print("Log: Login end" + DateTime.now().toString());
print(cubeUser);
}).catchError((error) {
print("Login error $error");
});
}
})

**Comment by TatankaConCube** [comment] 2021-03-18 17:12
duplicate of https://github.com/ConnectyCube/connectycube-flutter-sdk-releases/issues/12

**Closed by TatankaConCube** 2021-03-18 17:12 UTC

**Comment by shivanijha002** [comment] 2021-03-24 15:51
Issues are being closed without proper resolution. Same issue has been reported multiple times and I request you to take this issue seriously please.
No other API is slow except this specific API, so it is not justified that network only is causing the challenge.

**Comment by TatankaConCube** [comment] 2021-03-24 16:10
@shivanijha002  For chat functionality, we use the XMPP protocol. It requires a specific flow for establishing a Web socket connection and make a login to the chat. Every request/response takes some time, as result we have some delay during login to the chat. It is a protocol specification and we can't avoid it. We can only suggest you hide this process from a user and do it in the background invisible for your users.

> Issues are being closed without proper resolution.

Which issues do you mean? We try to resolve every issue related to or SDK or samples. If you have not resolved issues, please report these URLs to support@connectycube.com and we will try to resolve them

We are so sorry that you got a bad experience during using our product.
