### ISSUE TITLE
Receiving randomly push notifications like "You have 0 new messages"

### ISSUE THREAD

**Issue by zhukeev** [ConnectyCube/connectycube-flutter-samples#89] opened 2021-05-28 09:24 UTC
**Specify the sample to which the issue belongs (use [x]):**
[X] Chat sample
[ ] P2P Call sample
[ ] Conference Call sample

**Platform (use [x])**
[X] Android
[X] iOS

**Device info**
Manufacture: Apple/Xiaomi
Model: iPhone X/ Xiaomi Redmi Note 5
OS version: iOS 13.*/ Android 9

**Describe the bug:**
Receiving randomly push notification titled "You have 0 new messages"

**Steps to Reproduce:**
1. 
2.
3.
4.

**Logs:**
```
log here
```
or
[Gist log](https://gist.github.com/)

**Actual result:**

**Expected behavior:**

**Additional info**

**Comment by TatankaConCube** [comment] 2021-05-28 09:39
notified backend team about this issue, thank you for reporting

**Comment by TatankaConCube** [comment] 2021-06-14 09:10
@zhukeev do you still reproduce this issue?

**Comment by zhukeev** [comment] 2021-07-26 08:52
No, but currently not receiving any message from ConnectyCube

**Comment by osKlonowski** [comment] 2021-07-29 16:17
[X] Chat sample
[X] iOS
Device info
Manufacturer: Apple
Model: iPhone 11

Hi, I am still experiencing this issue. After chatting with another user inside the app, I close the app and can see a list of notifications "You have 0 new messages" which corresponds to the number of messages I sent inside the chat.

**Comment by TatankaConCube** [comment] 2021-09-02 14:37
If the issue is still actual, please notify us in the new ticket, closing this

**Closed by TatankaConCube** 2021-09-02 14:37 UTC
