### ISSUE TITLE
[Chat] Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by beheobong** [ConnectyCube/connectycube-flutter-samples#145] opened 2021-09-23 08:59 UTC
**Specify the sample to which the issue belongs (use [x]):**
[ x] Chat sample
[ ] P2P Call sample
[ ] Conference Call sample

I login my app and reload many time. Then call methob `cubeDialog.sendIsTypingStatus()`. That is bug? if it is bug: How to handle that problem?

E/flutter ( 8745):
I/chatty  ( 8745): uid=10160(gzr.bsd.dev) 1.ui identical 6 lines
E/flutter ( 8745): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: ErrorPacket: {type: auth, code: 401, condition: Condition.not_authorized, text: You must bind 
the resource first: http://www.xmpp.org/rfcs/rfc3920.html#bind}
E/flutter ( 8745):
E/flutter ( 8745): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: Null check operator used on a null value
E/flutter ( 8745): #0      new ChatManager.<anonymous closure> (package:xmpp_stone/src/chat/ChatManager.dart:30:72)
E/flutter ( 8745): #1      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter ( 8745): #2      _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 8745): #3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter ( 8745): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter ( 8745): #5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 8745): #6      _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter ( 8745): #7      _MapStream._handleData (dart:async/stream_pipe.dart:218:10)
E/flutter ( 8745): #8      _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter ( 8745): #9      _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter ( 8745): #10     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 8745): #11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter ( 8745): #12     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter ( 8745): #13     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter ( 8745): #14     _ForwardingStreamSubscription._add (dart:async/stream_pipe.dart:123:11)
E/flutter ( 8745): #15     _WhereStream._handleData (dart:async/stream_pipe.dart:195:12)
E/flutter ( 8745): #16     _ForwardingStreamSubscription._handleData (dart:async/stream_pipe.dart:153:13)
E/flutter ( 8745): #17     _rootRunUnary (dart:async/zone.dart:1436:47)
E/flutter ( 8745): #18     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
E/flutter ( 8745): #19     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
E/flutter ( 8745): #20     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:341:11)
E/flutter ( 8745): #21     _DelayedData.perform (dart:async/stream_impl.dart:591:14)
E/flutter ( 8745): #22     _StreamImplEvents.handleNext (dart:async/stream_impl.dart:706:11)
E/flutter ( 8745): #23     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:663:7)
E/flutter ( 8745): #24     _rootRun (dart:async/zone.dart:1420:47)
E/flutter ( 8745): #25     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 8745): #26     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter ( 8745): #27     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter ( 8745): #28     _rootRun (dart:async/zone.dart:1428:13)
E/flutter ( 8745): #29     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter ( 8745): #30     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter ( 8745): #31     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter ( 8745): #32     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter ( 8745): #33     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter ( 8745):
E/flutter ( 8745): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: ErrorPacket: {type: cancel, code: 503, condition: Condition.service_unavailable, text: Service not available.}
E/flutter ( 8745):
I/chatty  ( 8745): uid=10160(gzr.bsd.dev) 1.ui identical 6 lines
E/flutter ( 8745): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: ErrorPacket: {type: cancel, code: 503, condition: Condition.service_unavailable, text: Service not available.}
E/flutter ( 8745):

**Comment by TatankaConCube** [comment] 2021-09-23 13:38
Looks like you have some problems with the chat connection. Can you reproduce the same on our Chat sample? If yes, please provide steps, how can we reproduce the same issue on our side.

**Comment by TatankaConCube** [comment] 2021-10-06 08:15
Looks like the question is no longer actual, closing.

**Closed by TatankaConCube** 2021-10-06 08:15 UTC
